-- name: refresh_mc_user_ztk
-- 刷新 mc_user_ztk
INSERT INTO mc_user_ztk(ID,
                        NAME,
                        NO,
                        ACCOUNT_TYPE,
                        CERTIFICATE_CODE,
                        D_DELETE,
                        DATELASTMODIFIED,
                        EFFECTIVE_TIME_END,
                        EFFECTIVE_TIME_START,
                        GENDER,
                        IS_DELETE,
                        IS_EHR_SYNC,
                        LOGINNAME,
                        ORG,
                        PASSWORD_RESET,
                        PHOTO,
                        USER_GROUP_IDS,
                        WEIGHT,
                        ENCRYPTCERTIFICATE_CODE,
                        EXT_JOB_INFO_JOBSTATUS,
                        EXT_JOB_INFO_JOBCATEGORY,
                        EXT_JOB_INFO_HRJOBTYPE,
                        EXT_JOB_INFO_JOBTYPE,
                        BASE_STATION_SEQUENCE,
                        BASE_STATION_CODE,
                        BASE_STATION_SYSTEM,
                        BASE_STATION_GRADESYSTEM,
                        BASE_STATION_LEVEL,
                        BASE_STATION_GRADE,
                        BASE_STATION_NAME,
                        NAME_CARD_COMPANY_ID,
                        NAME_CARD_GENDER,
                        NAME_CARD_COMPANYPHONE,
                        NAME_CARD_ORGANIZATION,
                        NAME_CARD_NAME,
                        NAME_CARD_STATION,
                        NAME_CARD_MOBILE,
                        NAME_CARD_FOLK,
                        NAME_CARD_COMPANY,
                        NAME_CARD_EMAIL,
                        CONTACT_INFO_PHONE,
                        CONTACT_INFO_MOBILE,
                        CONTACT_INFO_EMAIL,
                        JOB_INFO_POSITIVE_DATE,
                        JOB_INFO_SPECIAL_JOB_YEARS,
                        JOB_INFO_WORK_DATE,
                        JOB_INFO_IS_SPECIAL_JOB,
                        JOB_INFO_LEAVE_DATE,
                        JOB_INFO_WORK_AGE,
                        JOB_INFO_IS_CORE_STAFF,
                        JOB_INFO_ENTERUNIT_DATE,
                        MSS_ACCOUNT,
                        MSS_BASESTATION,
                        MSS_BIRTHDAY,
                        MSS_CODE,
                        MSS_COMPANYCODE,
                        MSS_EMAIL,
                        MSS_ENGLISHNAME,
                        MSS_FIRSTMOBILE,
                        MSS_HRCODE,
                        MSS_HRID,
                        MSS_HRJOBTYPE,
                        MSS_ID,
                        MSS_IDENTITY,
                        MSS_IDENTITYCARD,
                        MSS_JOBCATEGORY,
                        MSS_JOBNUMBER,
                        MSS_JOBSTATUS,
                        MSS_JOBTYPE,
                        MSS_MAPID,
                        MSS_NAME,
                        MSS_ORGANIZATIONCODE,
                        MSS_SEX,
                        MSS_SORT,
                        MSS_STANDBYACCOUNT,
                        MSS_STATION,
                        MSS_STATIONGRADE,
                        MSS_STATIONGRADESYSTEM,
                        MSS_STATIONLEVEL,
                        MSS_STATIONSEQUENCE,
                        MSS_STATIONSYSTEM,
                        MSS_TELEPHONE,
                        MSS_TIME,
                        MSS_USERSTATUS,
                        SHOW_TELEPHONE,
                        SHOW_IDENTITY_CARD,
                        IDENTITY_CARD_JM,
                        BIRTH_YEAR,
                        BIRTH_MONTH,
                        BIRTH_DAY,
                        AGE,
                        DS_AREACODE,
                        AMOUNT,
                        TAG_IDS,
                        TAG_NAMES,
                        CERTIFICATE_TYPE,
                        MODIFYTIME)
SELECT TU.ID,
       TU.NAME,
       TU.NO,
       TU.ACCOUNT_TYPE,
       TU.CERTIFICATE_CODE,
       TU.D_DELETE,
       TU.DATELASTMODIFIED,
       TU.EFFECTIVE_TIME_END,
       TU.EFFECTIVE_TIME_START,
       TU.GENDER,
       TU.IS_DELETE,
       TU.IS_EHR_SYNC,
       TU.LOGINNAME,
       TU.ORG,
       TU.PASSWORD_RESET,
       TU.PHOTO,
       TU.USER_GROUP_IDS,
       TU.WEIGHT,
       TU.ENCRYPTCERTIFICATE_CODE,
       TU.EXT_JOB_INFO_JOBSTATUS,
       TU.EXT_JOB_INFO_JOBCATEGORY,
       TU.EXT_JOB_INFO_HRJOBTYPE,
       TU.EXT_JOB_INFO_JOBTYPE,
       TU.BASE_STATION_SEQUENCE,
       TU.BASE_STATION_CODE,
       TU.BASE_STATION_SYSTEM,
       TU.BASE_STATION_GRADESYSTEM,
       TU.BASE_STATION_LEVEL,
       TU.BASE_STATION_GRADE,
       TU.BASE_STATION_NAME,
       TU.NAME_CARD_COMPANY_ID,
       TU.NAME_CARD_GENDER,
       TU.NAME_CARD_COMPANYPHONE,
       TU.NAME_CARD_ORGANIZATION,
       TU.NAME_CARD_NAME,
       TU.NAME_CARD_STATION,
       TU.NAME_CARD_MOBILE,
       TU.NAME_CARD_FOLK,
       TU.NAME_CARD_COMPANY,
       TU.NAME_CARD_EMAIL,
       TU.CONTACT_INFO_PHONE,
       TU.CONTACT_INFO_MOBILE,
       TU.CONTACT_INFO_EMAIL,
       TU.JOB_INFO_POSITIVE_DATE,
       TU.JOB_INFO_SPECIAL_JOB_YEARS,
       TU.JOB_INFO_WORK_DATE,
       TU.JOB_INFO_IS_SPECIAL_JOB,
       TU.JOB_INFO_LEAVE_DATE,
       TU.JOB_INFO_WORK_AGE,
       TU.JOB_INFO_IS_CORE_STAFF,
       TU.JOB_INFO_ENTERUNIT_DATE,
       MU.ACCOUNT,
       MU.BASESTATION,
       MU.BIRTHDAY,
       MU.CODE,
       MU.COMPANYCODE,
       MU.EMAIL,
       MU.ENGLISHNAME,
       MU.FIRSTMOBILE,
       MU.HRCODE,
       MU.HRID,
       MU.HRJOBTYPE,
       MU.ID,
       MU.IDENTITY,
       MU.IDENTITYCARD,
       MU.JOBCATEGORY,
       MU.JOBNUMBER,
       MU.JOBSTATUS,
       MU.JOBTYPE,
       MU.MAPID,
       MU.NAME,
       MU.ORGANIZATIONCODE,
       MU.SEX,
       MU.SORT,
       MU.STANDBYACCOUNT,
       MU.STATION,
       MU.STATIONGRADE,
       MU.STATIONGRADESYSTEM,
       MU.STATIONLEVEL,
       MU.STATIONSEQUENCE,
       MU.STATIONSYSTEM,
       MU.TELEPHONE,
       MU.TIME,
       MU.USERSTATUS,
       IF(LENGTH(TU.NAME_CARD_MOBILE) = 11, CONCAT(LEFT(TU.NAME_CARD_MOBILE, 3), '****',
           RIGHT(TU.NAME_CARD_MOBILE, 4)), ''),
       IF(length(TU.CERTIFICATE_CODE) = 18, CONCAT(substr(TU.CERTIFICATE_CODE, 1, 4), '**********',
                                                   substr(TU.CERTIFICATE_CODE, 15, 4)
                                            ), ''),
       MD5(TU.CERTIFICATE_CODE),
       IF(length(TU.CERTIFICATE_CODE) = 18, substr(TU.CERTIFICATE_CODE, 7, 4), ''),
       IF(length(TU.CERTIFICATE_CODE) = 18, substr(TU.CERTIFICATE_CODE, 11, 2), ''),
       IF(length(TU.CERTIFICATE_CODE) = 18, substr(TU.CERTIFICATE_CODE, 13, 2), ''),
       IF(LENGTH(TU.CERTIFICATE_CODE) != 18, NULL, DATE_FORMAT(NOW(), '%Y') - substr(TU.CERTIFICATE_CODE, 7, 4)),
       O.GLOBLE,
       1,
       '',
       '',
       TU.CERTIFICATE_TYPE,
       NOW()
FROM d_telecom_user TU
         LEFT JOIN d_mss_user_mapping um
                   on TU.ID = um.USERID
         LEFT join d_mss_user MU
                   on um.MSSUID = MU.HRCODE
         LEFT JOIN mc_org_show O
                   ON TU.ORG = O.ID