-- name: refresh_mc_org_show
-- 刷新mc_org_show
INSERT INTO mc_org_show(ID,
                        IS_CORP,
                        NO,
                        NAME,
                        ABBREVIATION,
                        REMARK,
                        TYPE,
                        DISTRICT,
                        COMPANY_NATURE,
                        COMPANY_TYPE,
                        COMPANY_ID,
                        ORG_TYPE,
                        DEPT_LEVEL,
                        DEPT_TYPE,
                        LEGAL,
                        TAXPAYER_NUMBER,
                        WEBSITE,
                        BUSINESS_ADDRESS,
                        BUSINESS_CAPITAL,
                        AREA,
                        A_CODE,
                        PROVINCE,
                        P_CODE,
                        CITY,
                        C_CODE,
                        CTCPROVINCE,
                        CTCAREA,
                        CTCCITY,
                        LEAF,
                        OLEVEL,
                        PARENT,
                        WEIGHT,
                        ANCESTORS,
                        GLOBLE,
                        IS_DELETE,
                        YEAR,
                        MONTH,
                        MSSID,
                        MSSIDENTITY,
                        MSSCODE,
                        MSSHRCODE,
                        MSSNAME,
                        MSSTYPE,
                        MSSPARENTCOMPANYCODE,
                        MSSPARENTDEPARTMENTCODE,
                        MSSSTATUS,
                        MSSCHIEFLEADER,
                        MSSDEPUTYLEADER,
                        MSSCOMPANYTYPE,
                        MSSDEPARTMENTTYPE,
                        MSSDEPARTMENTLEVEL,
                        CODE_3,
                        CODE_4,
                        CODE_5,
                        CODE_6,
                        CODE_7,
                        CODE_8,
                        CODE_9,
                        DIRECTLY_NUM,
                        ATTACHED_NUM,
                        COMPANY_NAME,
                        COMPANY_GLOBLE,
                        COMPANY_GLOBLE_NAME,
                        GLOBLE_NAME,
                        LOG_SDATE)
SELECT TE.ID,
       TE.IS_CORP,
       TE.NO,
       TE.NAME,
       TE.ABBREVIATION,
       TE.REMARK,
       TE.TYPE,
       ''                                                                                   AS DISTRICT,
       ''                                                                                   AS COMPANY_NATURE,
       TE.COMPANY_TYPE,
       TE.COMPANY_ID,
       TE.ORG_TYPE,
       TE.DEPT_LEVEL,
       TE.DEPT_TYPE,
       TE.LEGAL,
       TE.TAXPAYER_NUMBER,
       TE.WEBSITE,
       TE.BUSINESS_ADDRESS,
       TE.BUSINESS_CAPITAL,
       ''                                                                                   AS AREA,
       ''                                                                                   AS A_CODE,
       TE.PROVINCE,
       TE.P_CODE,
       TE.CITY                                                                              AS CITY,
       TE.C_CODE                                                                            AS C_CODE,
       ''                                                                                   AS CTCPROVINCE,
       ''                                                                                   AS CTCAREA,
       ''                                                                                   AS CTCCITY,
       TR.LEAF                                                                              AS LEAF,
       TRUNCATE((LENGTH(tr.ancestors) - LENGTH(REPLACE(tr.ancestors, '，', ''))) / 3, 0) + 2 AS OLEVEL,
       TR.PARENT                                                                            AS PARENT,
       TE.WEIGHT                                                                            AS WEIGHT,
       TR.ANCESTORS                                                                         AS ANCESTORS,
       TE.FULL_PATH_ID                                                                      AS GLOBLE,
       TE.IS_DELETE                                                                         AS IS_DELETE,
       TE.YEAR AS YEAR,
                       TE.MONTH                                                                             AS MONTH,
                       MO.ID                                                                                AS MSSID,
                       MO.IDENTITY                                                                          AS MSSIDENTITY,
                       MO.CODE                                                                              AS MSSCODE,
                       MO.HRCODE                                                                            AS MSSHRCODE,
                       MO.NAME                                                                              AS MSSNAME,
                       MO.TYPE                                                                              AS MSSTYPE,
                       MO.PARENTCOMPANYCODE                                                                 AS MSSPARENTCOMPANYCODE,
                       MO.PARENTDEPARTMENTCODE                                                              AS MSSPARENTDEPARTMENTCODE,
                       MO.STATUS                                                                            AS MSSSTATUS,
                       ''                                                                                   AS MSSCHIEFLEADER,
                       ''                                                                                   AS MSSDEPUTYLEADER,
                       MO.COMPANYTYPE                                                                       AS MSSCOMPANYTYPE,
                       ''                                                                                   AS MSSDEPARTMENTTYPE,
                       ''                                                                                   AS MSSDEPARTMENTLEVEL,
                       IF((LENGTH(TR.FULL_PATH_ID) - LENGTH(REPLACE(TR.FULL_PATH_ID, ',', ''))) / LENGTH(',') >= 2,
                          SUBSTRING_INDEX(SUBSTRING_INDEX(TR.FULL_PATH_ID, ',', 3), ',', -1), NULL)         AS CODE_3,
                       IF((LENGTH(TR.FULL_PATH_ID) - LENGTH(REPLACE(TR.FULL_PATH_ID, ',', ''))) / LENGTH(',') >= 3,
                          SUBSTRING_INDEX(SUBSTRING_INDEX(TR.FULL_PATH_ID, ',', 4), ',', -1), NULL)         AS CODE_4,
                       IF((LENGTH(TR.FULL_PATH_ID) - LENGTH(REPLACE(TR.FULL_PATH_ID, ',', ''))) / LENGTH(',') >= 4,
                          SUBSTRING_INDEX(SUBSTRING_INDEX(TR.FULL_PATH_ID, ',', 5), ',', -1), NULL)         AS CODE_5,
                       IF((LENGTH(TR.FULL_PATH_ID) - LENGTH(REPLACE(TR.FULL_PATH_ID, ',', ''))) / LENGTH(',') >= 5,
                          SUBSTRING_INDEX(SUBSTRING_INDEX(TR.FULL_PATH_ID, ',', 6), ',', -1), NULL)         AS CODE_6,
                       IF((LENGTH(TR.FULL_PATH_ID) - LENGTH(REPLACE(TR.FULL_PATH_ID, ',', ''))) / LENGTH(',') >= 6,
                          SUBSTRING_INDEX(SUBSTRING_INDEX(TR.FULL_PATH_ID, ',', 7), ',', -1), NULL)         AS CODE_7,
                       IF((LENGTH(TR.FULL_PATH_ID) - LENGTH(REPLACE(TR.FULL_PATH_ID, ',', ''))) / LENGTH(',') >= 7,
                          SUBSTRING_INDEX(SUBSTRING_INDEX(TR.FULL_PATH_ID, ',', 8), ',', -1), NULL)         AS CODE_8,
                       IF((LENGTH(TR.FULL_PATH_ID) - LENGTH(REPLACE(TR.FULL_PATH_ID, ',', ''))) / LENGTH(',') >= 8,
                          SUBSTRING_INDEX(SUBSTRING_INDEX(TR.FULL_PATH_ID, ',', 9), '，', -1), NULL)         AS CODE_9,
                       (SELECT COUNT(U.ID) FROM mc_user_ztk U WHERE U.ORG = TE.ID)                          AS DIRECTLY_NUM,
                       0                                                                                    AS ATTACHED_NUM,
                       TR.NAME                                                                              AS COMPANY_NAME,
                       TR.FULL_PATH_ID                                                                      AS COMPANY_GLOBLE,
                       TR.FULL_PATH_NAME                                                                    AS COMPANY_GLOBLE_NAME,
                       TE.FULL_PATH_NAME                                                                    AS GLOBLE_NAME,
                       DATE_FORMAT(NOW(), '%Y-%m-%d')                                                       AS LOG_SDATE
FROM d_telecom_org TE
    LEFT JOIN d_telecom_org_tree TR
ON TE.ID = TR.ID
    LEFT JOIN d_mss_org_mapping MOM
    ON TE.ID = MOM.CODE
    LEFT JOIN d_mss_org MO
    ON MOM.MSSCODE = MO.HRCODE AND MO.STATUS = '1'